export enum Role {
    ORGANIZER = "ORGANIZER",
    ATTENDEE = "ATTENDEE"
}

export enum EventCategory {
    MUSIC_CONCERTS = "MUSIC_CONCERTS",
    STANDUP_COMEDY = "STANDUP_COMEDY",
    IMPROV_COMEDY = "IMPROV_COMEDY",
    THEATER_PERFORMANCES = "THEATER_PERFORMANCES",
    MUSICALS = "MUSICALS",
    OPERA = "OPERA",
    DANCE_PERFORMANCES = "DANCE_PERFORMANCES",
    MAGIC_SHOWS = "MAGIC_SHOWS",
    FESTIVALS = "FESTIVALS",
    SPORTS_EVENTS = "SPORTS_EVENTS",
    TALENT_SHOWS = "TALENT_SHOWS",
    WORKSHOPS_CLASSES = "WORKSHOPS_CLASSES",
    CONFERENCES_TALKS = "CONFERENCES_TALKS",
    FAMILY_KIDS_EVENTS = "FAMILY_KIDS_EVENTS",
    VIRTUAL_EVENTS = "VIRTUAL_EVENTS",
    OTHERS = "OTHERS"
}

export enum BookingStatus {
    FAILED = 'FAILED',
    PENDING = 'PENDING',
    SUCCESSFUL = 'SUCCESSFUL'
}

export enum SeatStatus {
    AVAILABLE = 'AVAILABLE',
    BOOKED = 'BOOKED',
    LOCKED = 'LOCKED',
}
